create table if not exists public.bets (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  event_name text not null,
  market_name text not null,
  bookmaker text,
  bet_date date not null,
  stake numeric(10, 2) not null check (stake >= 0),
  odds numeric(10, 2) not null check (odds >= 1),
  status text not null check (status in ('pending', 'won', 'lost', 'void')),
  profit numeric(10, 2) not null default 0,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists bets_user_id_idx on public.bets (user_id);
create index if not exists bets_bet_date_idx on public.bets (bet_date desc);

alter table public.bets enable row level security;

drop policy if exists "Users can read their own bets" on public.bets;
drop policy if exists "Users can insert their own bets" on public.bets;
drop policy if exists "Users can update their own bets" on public.bets;
drop policy if exists "Users can delete their own bets" on public.bets;

create policy "Users can read their own bets"
on public.bets
for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "Users can insert their own bets"
on public.bets
for insert
to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "Users can update their own bets"
on public.bets
for update
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id)
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "Users can delete their own bets"
on public.bets
for delete
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);
