create table if not exists public.bets (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  tipster text,
  bookie text,
  sport text,
  event_name text not null,
  market_name text not null,
  bet_type text not null default 'Other',
  bet_date date not null,
  stake numeric(10, 2) not null check (stake >= 0),
  odds numeric(10, 2) not null check (odds >= 1),
  status text not null check (status in ('pending', 'won', 'lost', 'half_won', 'half_lost', 'cashout', 'partial_void', 'void')),
  settlement_return numeric(10, 2),
  profit numeric(10, 2) not null default 0,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.tipsters (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.bookies (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.sports (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

alter table public.bets add column if not exists tipster text;
alter table public.bets add column if not exists bookie text;
alter table public.bets add column if not exists sport text;
alter table public.bets add column if not exists bet_type text not null default 'Other';
alter table public.bets add column if not exists settlement_return numeric(10, 2);

update public.bets
set
  bookie = coalesce(bookie, bookmaker),
  bet_type = case
    when market_name is null or btrim(market_name) = '' then 'Other'
    when lower(market_name) like '%over%' or lower(market_name) like '%mais%' or lower(market_name) like '%acima%' then 'Overs'
    when lower(market_name) like '%under%' or lower(market_name) like '%menos%' or lower(market_name) like '%abaixo%' then 'Unders'
    when lower(market_name) like '%btts no%' then 'BTTS NO'
    when lower(market_name) like '%btts yes%' then 'BTTS YES'
    when lower(market_name) like '%result%' then 'Result'
    when lower(market_name) like '%handicap%' then 'Handicap'
    else 'Other'
  end
where bookie is null or bet_type is null or bet_type = 'Other';

create index if not exists bets_user_id_idx on public.bets (user_id);
create index if not exists bets_bet_date_idx on public.bets (bet_date desc);
create index if not exists bets_tipster_idx on public.bets (tipster);
create index if not exists bets_bookie_idx on public.bets (bookie);
create index if not exists bets_sport_idx on public.bets (sport);
create index if not exists bets_bet_type_idx on public.bets (bet_type);
create index if not exists tipsters_user_id_idx on public.tipsters (user_id);
create index if not exists bookies_user_id_idx on public.bookies (user_id);
create index if not exists sports_user_id_idx on public.sports (user_id);

insert into public.tipsters (user_id, name)
select distinct user_id, tipster
from public.bets
where tipster is not null and btrim(tipster) <> ''
on conflict (user_id, name) do nothing;

insert into public.bookies (user_id, name)
select distinct user_id, bookie
from public.bets
where bookie is not null and btrim(bookie) <> ''
on conflict (user_id, name) do nothing;

insert into public.sports (user_id, name)
select distinct user_id, sport
from public.bets
where sport is not null and btrim(sport) <> ''
on conflict (user_id, name) do nothing;

alter table public.bets enable row level security;
alter table public.tipsters enable row level security;
alter table public.bookies enable row level security;
alter table public.sports enable row level security;

drop policy if exists "Users can read their own bets" on public.bets;
drop policy if exists "Users can insert their own bets" on public.bets;
drop policy if exists "Users can update their own bets" on public.bets;
drop policy if exists "Users can delete their own bets" on public.bets;
drop policy if exists "Users can read their own tipsters" on public.tipsters;
drop policy if exists "Users can insert their own tipsters" on public.tipsters;
drop policy if exists "Users can read their own bookies" on public.bookies;
drop policy if exists "Users can insert their own bookies" on public.bookies;
drop policy if exists "Users can read their own sports" on public.sports;
drop policy if exists "Users can insert their own sports" on public.sports;

create policy "Users can read their own bets"
on public.bets
for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "Users can insert their own bets"
on public.bets
for insert
to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "Users can update their own bets"
on public.bets
for update
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id)
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "Users can delete their own bets"
on public.bets
for delete
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "Users can read their own tipsters"
on public.tipsters
for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "Users can insert their own tipsters"
on public.tipsters
for insert
to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "Users can read their own bookies"
on public.bookies
for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "Users can insert their own bookies"
on public.bookies
for insert
to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "Users can read their own sports"
on public.sports
for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "Users can insert their own sports"
on public.sports
for insert
to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);
